export const FETCH_AUTH_HEALTH_FAILURE = "auth/FETCH_AUTH_HEALTH_FAILURE";
export const FETCH_AUTH_HEALTH_SUCCESS = "auth/FETCH_AUTH_HEALTH_SUCCESS";
export const FETCH_AUTH_HEALTH_BEGIN = "auth/FETCH_AUTH_HEALTH_BEGIN";
